# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='lifetime_in_days',
            field=models.IntegerField(default=30),
        ),
    ]
