# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0005_auto_20170611_0510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
