# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0009_auto_20170612_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajirauser',
            name='resume',
            field=models.FileField(default='No resume uploaded', max_length=50, upload_to='media/resumes/%Y/%m/%d'),
        ),
    ]
