# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0010_ajirauser_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajirauser',
            name='company_name',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
