# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0011_auto_20170614_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajirauser',
            name='job_title',
            field=models.CharField(default='N/A', max_length=60),
        ),
    ]
