# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0016_auto_20170614_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='careerinterests',
            name='job_locations',
            field=models.ManyToManyField(to='ajira.Location'),
        ),
        migrations.AddField(
            model_name='careerinterests',
            name='job_titles',
            field=models.ManyToManyField(to='ajira.JobTitle'),
        ),
        migrations.AddField(
            model_name='ajirauser',
            name='career_interests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ajira.CareerInterests'),
        ),
    ]
