# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajira', '0017_auto_20170617_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerinterests',
            name='job_types',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('IN', 'Internship'), ('T', 'Tenda/Contract')], default='FT', max_length=10),
        ),
    ]
